name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flywind:
    path: ../../flywind
  go_router: ^16.2.4
  provider: ^6.1.5+1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  web3dart: ^2.7.3
  dart_nostr:
    path: ../../dart_nostr
  flutter_dotenv: ^6.0.0
  web_socket_channel: ^2.4.0
  lucide_icons: ^0.257.0
  blockies: ^0.1.2
  toastification: ^3.0.3
  http: ^1.5.0
  collection: ^1.19.1
  archive: ^4.0.7
  smartcontracts:
    git:
      url: https://github.com/citizenwallet/smartcontracts.git
      ref: v0.0.106
  contractforge:
    git:
      url: https://github.com/citizenwallet/contractforge.git
      ref: v0.0.19
  universal_io: ^2.2.2
  file_picker: ^10.3.3
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/config/communities.json
    - assets/words/nouns.json
    - assets/icons/profile.png
    - packages/smartcontracts/contracts/accounts/Account.abi.json
    - packages/smartcontracts/contracts/accounts/AccountFactory.abi.json
    - packages/smartcontracts/contracts/external/DERC20.abi.json
    - packages/smartcontracts/contracts/accounts/Account.abi.json
    - packages/smartcontracts/contracts/external/SimpleAccountFactory.abi.json
    - packages/smartcontracts/contracts/accounts/TokenEntryPoint.abi.json
    - packages/smartcontracts/contracts/standards/IAccessControlUpgradeable.abi.json
    - packages/smartcontracts/contracts/apps/SimpleFaucet.abi.json
    - packages/smartcontracts/contracts/standards/ERC20.abi.json
    - packages/smartcontracts/contracts/standards/ERC1155.abi.json
    - packages/smartcontracts/contracts/apps/Profile.abi.json
    - packages/smartcontracts/contracts/external/CardFactory.abi.json
    - packages/contractforge/abi/CardManagerModule.json
    - packages/contractforge/abi/Safe.json
    - packages/contractforge/abi/CommunityModule.json
    - packages/contractforge/abi/TwoFAFactory.json
    - packages/contractforge/abi/SessionManagerModule.json
